common:
  imu_topic: /livox/imu
  # imu_topic: /mavros/imu/data

  lid_topic: /livox/lidar
  time_offset_lidar_to_imu: 0.0
  time_sync_en: false
mapping:
  acc_cov: 0.1
  b_acc_cov: 0.0001
  b_gyr_cov: 0.0001
  det_range: 100.0
  extrinsic_R:
  - 1
  - 0
  - 0
  - 0
  - 1
  - 0
  - 0
  - 0
  - 1
  # - 0.963621
  # - -0.033193
  # - 0.265203
  # - 0.036607
  # - 0.999298
  # - -0.007940
  # - -0.264754
  # - 0.017359
  # - 0.964160
  # - 0.0
  # - 1.0
  # - 0.0
  # - -0.965652
  # - 0.0
  # - 0.264754
  # - 0.264754
  # - 0.0
  # - 0.964160
  extrinsic_T:
  # - -0.011
  # - -0.02329
  # - 0.04412
  # - -0.011
  # - -0.02329
  # - 0.04412
  - 0.00
  - 0
  - 0.00
  extrinsic_est_en: false
  fov_degree: 360
  gyr_cov: 0.1
pcd_save:
  interval: -1
  pcd_save_en: false
preprocess:
  blind: 0.5
  lidar_type: 1
  scan_line: 4
publish:
  dense_publish_en: true
  path_en: false
  scan_bodyframe_pub_en: false
  scan_publish_en: true
  debug_circular_scan_publish_en: false
  debug_circular_cloud_radius: 2.0
  no_point_filter_scan_publish_en: true
  fov_yaw_offset_deg: 0.0
lidar_body:
  rotation: [1, 0, 0, 0, 1, 0, 0, 0, 1]
  translation: [0, 0, 0]
map:
  incremental: true
  load_from_pcd: false
  pcd_file: new1.pcd
  save_on_exit: true
  save_file: new.pcd
sched:
  affinity_enable: true
  core_count: 8
  affinity_cores: [0, 1, 2]
cpu_monitor:
  enable: true
  filter_type: 0
  filter_param1: 15
  filter_param2: 10
  freq: 10
