common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/mavros/imu/data"

preprocess:
    lidar_type: 1                # Livox series LiDAR
    feature_extract_en: false
    scan_line: 6
    blind: 1

initialization:
    cut_frame_num: 5             # smoke: 5 frames for quick calibration
    orig_odom_freq: 10
    mean_acc_norm: 9.805         # Pixhawk IMU
    online_refine_time: 20       # shortened for smoke test
    data_accum_length: 200
    Rot_LI_cov: [ 0.00005, 0.00005, 0.00005 ]
    Trans_LI_cov: [ 0.00001, 0.00001, 0.00001 ]

mapping:
    filter_size_surf: 0.05
    filter_size_map: 0.15
    gyr_cov: 2
    acc_cov: 2
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    det_range: 100.0

publish:
    path_en:  true
    scan_publish_en:  true
    dense_publish_en: true
    scan_bodyframe_pub_en: false

pcd_save:
    pcd_save_en: false
    interval: -1
