import { $ } from "bun";
import { readFileSync } from "fs";
import { runSSH, runSSHStreaming, checkSSH } from "../core/ssh";
import {
  REGISTRY_PORT,
  REGISTRY_DIRECT_PORT,
  DOCKER_IMAGES,
} from "../core/config";
import { getDevelHostUSBIP, getDevelHostLANIP } from "../core/network";
import { REGISTRY_CERT } from "../core/registry-paths";
import { certCovers } from "./registry";

const REMOTE_DOCKER_CERT_DIR = "/etc/docker/certs.d";

async function installRegistryTrust(registryHost: string, registryPort: number) {
  const cert = readFileSync(REGISTRY_CERT);
  const encodedCert = Buffer.from(cert).toString("base64");
  const certDir = `${REMOTE_DOCKER_CERT_DIR}/${registryHost}:${registryPort}`;
  const certPath = `${certDir}/ca.crt`;
  const cmd = [
    `sudo mkdir -p ${$.escape(certDir)}`,
    `printf %s ${$.escape(encodedCert)} | base64 -d | sudo tee ${$.escape(certPath)} >/dev/null`,
    `sudo chmod 0644 ${$.escape(certPath)}`,
  ].join("; ");

  const result = await runSSH(cmd, false);
  if (result.exitCode !== 0) {
    const detail = result.stderr.trim() || result.stdout.trim() || "no output";
    throw new Error(`failed to install registry trust on Jetson (exit ${result.exitCode}):\n${detail}`);
  }
}

export async function cmdDockerPush() {
  console.log("[docker-push] Pushing fleet images to registry ...");

  // 1. Check SSH to dev-device
  const ok = await checkSSH();
  if (!ok) {
    console.log("[docker-push] Dev device not reachable via USB. Is it connected?");
    process.exit(1);
  }

  // 2. Prefer USB for large image pushes. The registry cert generated by
  // `registry start` includes both USB and LAN SANs.
  const lanIP = getDevelHostLANIP();
  const usbIP = getDevelHostUSBIP();
  const registryHost = usbIP || lanIP;
  if (!registryHost) {
    console.log("[docker-push] Cannot detect dev-host registry IP.");
    process.exit(1);
  }
  const registryPort = REGISTRY_DIRECT_PORT;
  console.log(`[docker-push] Pushing directly to ${registryHost}:${registryPort}`);

  // 3. Verify registry TLS cert covers the push target
  if (!certCovers([registryHost])) {
    console.log(`[docker-push] Registry cert on dev-host does not cover push target ${registryHost}.`);
    console.log(`[docker-push] Run 'bun run registry start' to regenerate the cert, then retry.`);
    process.exit(1);
  }

  await installRegistryTrust(registryHost, registryPort);

  // 4. Verify images exist on Jetson
  const checkCmd = [
    "set -euo pipefail",
    ...DOCKER_IMAGES.map(({ image }) => `docker image inspect ${$.escape(image)} >/dev/null`),
    `echo IMAGES_OK`,
  ].join("; ");
  const checkResult = await runSSH(checkCmd, false);
  if (checkResult.exitCode !== 0 || !checkResult.stdout.includes("IMAGES_OK")) {
    console.log("[docker-push] One or more fleet images are missing on Jetson:");
    for (const { label, image } of DOCKER_IMAGES) {
      console.log(`  ${label.padEnd(5)} ${image}`);
    }
    console.log("[docker-push] Run 'bun run docker-dbuild' and 'bun run docker-dbuild calib' first.");
    process.exit(1);
  }

  // 5. Tag and push (direct to registry, bypassing tracker proxy)
  const pushCmd = [
    "set -euo pipefail",
    ...DOCKER_IMAGES.flatMap(({ image }) => {
      const tag = `${registryHost}:${registryPort}/${image}`;
      return [
        `docker tag ${$.escape(image)} ${$.escape(tag)}`,
        `docker push ${$.escape(tag)}`,
      ];
    }),
  ].join("; ");

  console.log("[docker-push] Tagging and pushing fleet images ...");
  const exitCode = await runSSHStreaming(pushCmd);
  if (exitCode !== 0) {
    throw new Error(`docker push failed (exit ${exitCode})`);
  }
  console.log("[docker-push] Images pushed successfully.");
  const pullHost = lanIP || registryHost;
  console.log("[docker-push] Fleet devices:");
  for (const { label, image } of DOCKER_IMAGES) {
    console.log(`  ${label.padEnd(5)} docker pull ${pullHost}:${REGISTRY_PORT}/${image}`);
  }
}
