import { $ } from "bun";
import { readFileSync } from "fs";
import { runSSH, runSSHStreaming, checkSSH } from "../core/ssh";
import {
  REGISTRY_PORT,
  REGISTRY_DIRECT_PORT,
  DOCKER_IMAGE,
} from "../core/config";
import { getDevelHostUSBIP, getDevelHostLANIP } from "../core/network";
import { REGISTRY_CERT } from "../core/registry-paths";

const REMOTE_DOCKER_CERT_DIR = "/etc/docker/certs.d";

async function installRegistryTrust(registryHost: string, registryPort: number) {
  const cert = readFileSync(REGISTRY_CERT);
  const encodedCert = Buffer.from(cert).toString("base64");
  const certDir = `${REMOTE_DOCKER_CERT_DIR}/${registryHost}:${registryPort}`;
  const certPath = `${certDir}/ca.crt`;
  const cmd = [
    `sudo mkdir -p ${$.escape(certDir)}`,
    `printf %s ${$.escape(encodedCert)} | base64 -d | sudo tee ${$.escape(certPath)} >/dev/null`,
    `sudo chmod 0644 ${$.escape(certPath)}`,
  ].join("; ");

  const result = await runSSH(cmd, false);
  if (result.exitCode !== 0) {
    const detail = result.stderr.trim() || result.stdout.trim() || "no output";
    throw new Error(`failed to install registry trust on Jetson (exit ${result.exitCode}):\n${detail}`);
  }
}

export async function cmdDockerPush() {
  console.log("[docker-push] Pushing fastlio-jetson to registry ...");

  // 1. Check SSH to dev-device
  const ok = await checkSSH();
  if (!ok) {
    console.log("[docker-push] Dev device not reachable via USB. Is it connected?");
    process.exit(1);
  }

  // 2. Prefer USB for large image pushes. The registry cert generated by
  // `registry start` includes both USB and LAN SANs.
  const lanIP = getDevelHostLANIP();
  const usbIP = getDevelHostUSBIP();
  const registryHost = usbIP || lanIP;
  if (!registryHost) {
    console.log("[docker-push] Cannot detect dev-host registry IP.");
    process.exit(1);
  }
  const registryPort = REGISTRY_DIRECT_PORT;
  console.log(`[docker-push] Pushing directly to ${registryHost}:${registryPort}`);
  await installRegistryTrust(registryHost, registryPort);

  // 3. Verify image exists on Jetson
  const checkCmd = [
    `docker image inspect ${$.escape(DOCKER_IMAGE)} >/dev/null 2>&1`,
    `echo IMAGE_OK`,
  ].join("; ");
  const checkResult = await runSSH(checkCmd, false);
  if (checkResult.exitCode !== 0 || !checkResult.stdout.includes("IMAGE_OK")) {
    console.log(`[docker-push] Image '${DOCKER_IMAGE}' not found on Jetson.`);
    console.log("[docker-push] Run 'bun run docker-dbuild' first.");
    process.exit(1);
  }

  // 4. Tag and push (direct to registry, bypassing tracker proxy)
  const tag = `${registryHost}:${registryPort}/${DOCKER_IMAGE}`;
  const pushCmd = [
    "set -euo pipefail",
    `docker tag ${$.escape(DOCKER_IMAGE)} ${$.escape(tag)}`,
    `docker push ${$.escape(tag)}`,
  ].join("; ");

  console.log(`[docker-push] Tagging and pushing: ${tag} ...`);
  const exitCode = await runSSHStreaming(pushCmd);
  if (exitCode !== 0) {
    throw new Error(`docker push failed (exit ${exitCode})`);
  }
  console.log("[docker-push] Image pushed successfully.");
  const pullHost = lanIP || registryHost;
  console.log(`[docker-push] Fleet devices: docker pull ${pullHost}:${REGISTRY_PORT}/${DOCKER_IMAGE}`);
}
